"""SCPI language primitives."""

from .active_device import (
    GainCompressionState,
    NoiseFigureState,
    PNAActiveDeviceSystem,
    register_active_device_commands,
)
from .advanced import AdvancedChannel, AdvancedMarker, PNAAdvancedSystem, register_advanced_commands

from .acquisition import (
    AcquisitionChannel,
    AcquisitionController,
    AcquisitionState,
    OperationConditionBit,
    SweepMode,
    TriggerSource,
    register_acquisition_commands,
)
from .capabilities import (
    CapabilityError,
    CompatibilityMode,
    PNACapabilities,
    detect_pna_model,
    register_capability_commands,
)
from .common import register_common_commands
from .errors import (
    ErrorCategory,
    ErrorQueue,
    NO_ERROR,
    QUEUE_OVERFLOW,
    SCPIErrorRecord,
    StandardEventBit,
    classify_error,
    standard_error,
)
from .operations import (
    OperationHandle,
    OperationManager,
    OperationState,
    OperationStateError,
    OperationTimeout,
    register_operation_commands,
)
from .manifest import (
    CommandManifest,
    ManifestCommand,
    ManifestError,
    command_spec_key,
    coverage_report,
    load_command_manifest,
    registry_implementation_keys,
)
from .measurements import (
    ChannelState,
    MarkerState,
    MeasurementState,
    PNAMeasurementSystem,
    TraceState,
    WindowState,
    register_measurement_commands,
)
from .mixer import (
    FrequencyOffsetRange,
    MixerChannel,
    MixerSegment,
    PNAMixerSystem,
    register_mixer_commands,
)
from .output import (
    BinaryResponse,
    ByteOrder,
    DataEncoding,
    DataFormat,
    OutputQueue,
    OutputQueueFull,
    register_format_commands,
)
from .pna_data import PNADataSystem, register_pna_data_commands
from .pulse import PulseChannel, PulseGenerator, PNAPulseSystem, register_pulse_commands
from .parser import (
    BinaryBlock,
    Command,
    HeaderSegment,
    NumericValue,
    Parameter,
    ParameterKind,
    ProgramMessage,
    SCPIParseError,
    mnemonic_matches,
    parse_program_message,
)
from .registry import (
    CommandRegistry,
    CommandSpec,
    HeaderNode,
    Invocation,
    ParameterSpec,
    ParameterType,
    ResolvedCommand,
    SCPICommandError,
)
from .status import (
    EVENT_REGISTER_MASK,
    STATUS_REGISTER_MASK,
    StatusByteBit,
    StatusRegisterGroup,
    StatusSystem,
    register_status_commands,
)
from .sweeps import PNASweepChannel, PNASweepSystem, register_sweep_commands
from .scalar_data import ScalarConfiguration, ScalarScenarioSystem, register_scalar_commands
from .state_files import PNAStateFileStore, register_state_file_commands
from .time_domain import PNATimeDomainSystem, TimeDomainChannel, register_time_domain_commands

__all__ = [
    "GainCompressionState",
    "AdvancedChannel",
    "AdvancedMarker",
    "NoiseFigureState",
    "PNAActiveDeviceSystem",
    "PNAAdvancedSystem",
    "register_active_device_commands",
    "register_advanced_commands",
    "BinaryBlock",
    "BinaryResponse",
    "ByteOrder",
    "CapabilityError",
    "ChannelState",
    "CompatibilityMode",
    "AcquisitionChannel",
    "AcquisitionController",
    "AcquisitionState",
    "Command",
    "CommandRegistry",
    "CommandManifest",
    "CommandSpec",
    "DataEncoding",
    "DataFormat",
    "ErrorCategory",
    "ErrorQueue",
    "EVENT_REGISTER_MASK",
    "HeaderSegment",
    "HeaderNode",
    "Invocation",
    "ManifestCommand",
    "ManifestError",
    "MarkerState",
    "MixerChannel",
    "MixerSegment",
    "MeasurementState",
    "NumericValue",
    "NO_ERROR",
    "OperationHandle",
    "OperationConditionBit",
    "OperationManager",
    "OperationState",
    "OperationStateError",
    "OperationTimeout",
    "OutputQueue",
    "OutputQueueFull",
    "Parameter",
    "ParameterKind",
    "ParameterSpec",
    "ParameterType",
    "PNACapabilities",
    "PNADataSystem",
    "PNAPulseSystem",
    "PNAMeasurementSystem",
    "PNAMixerSystem",
    "PNASweepChannel",
    "PNASweepSystem",
    "PNAStateFileStore",
    "PNATimeDomainSystem",
    "ProgramMessage",
    "PulseChannel",
    "PulseGenerator",
    "FrequencyOffsetRange",
    "QUEUE_OVERFLOW",
    "SCPIParseError",
    "ScalarConfiguration",
    "ScalarScenarioSystem",
    "ResolvedCommand",
    "SCPICommandError",
    "SCPIErrorRecord",
    "STATUS_REGISTER_MASK",
    "StandardEventBit",
    "StatusByteBit",
    "StatusRegisterGroup",
    "StatusSystem",
    "SweepMode",
    "TriggerSource",
    "TraceState",
    "TimeDomainChannel",
    "WindowState",
    "classify_error",
    "command_spec_key",
    "coverage_report",
    "detect_pna_model",
    "load_command_manifest",
    "mnemonic_matches",
    "parse_program_message",
    "register_status_commands",
    "registry_implementation_keys",
    "register_operation_commands",
    "register_acquisition_commands",
    "register_capability_commands",
    "register_common_commands",
    "register_format_commands",
    "register_measurement_commands",
    "register_mixer_commands",
    "register_pna_data_commands",
    "register_pulse_commands",
    "register_scalar_commands",
    "register_sweep_commands",
    "register_state_file_commands",
    "register_time_domain_commands",
    "standard_error",
]
